### ISSUE TITLE
climate.set_preset_mode winter does not exist anymore

### ISSUE THREAD

**Issue by huuub** [MislavMandaric/home-assistant-vaillant-vsmart#271]
Well it was an issue. I figured out it changed to none instead of winter in Home assistant?

```
service: climate.set_preset_mode
data:
  preset_mode: none ## was winter
target:
  entity_id: climate.thermostaat
```

**Comment by MislavMandaric** [comment]
Hey @huuub.

Depends on what you were using this service call for 😅

If you used if for toggling between away and home, then you are right - switching between `away` and `none` presets is what you would do.

But if you want to switch between summer and winter modes of operation for the boiler itself (ie. winter meaning "both heating and hot water" and summer meaning "heating is off, only hot water") then you should switch to using the water heater entity and its operation mode service.

Example for setting to summer mode:

```
service: water_heater.set_operation_mode
data:
  operation: hot_water_only
target:
  entity_id: water_heater.{name}
```

Example for setting to winter mode:

```
service: water_heater.set_operation_mode
data:
  operation: heating
target:
  entity_id: water_heater.{name}
```

Hope this clears it up a bit. It's a breaking change in v0.9.0, which is frustrating, but it makes much more sense than what it was before.
